import "./globals.css";
import AppSidebar from "./admin/sidebar"; // Göreceli yol, belirttiğin gibi

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex min-h-screen">
          <div className="w-64">
            <AppSidebar />
          </div>
          <main className="flex-1 p-4">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
